// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID       int64       `json:"id"`
	Uuid     uuid.UUID   `json:"uuid"`
	Title    pgtype.Text `json:"title"`
	AuthorID pgtype.Int4 `json:"author_id"`
}

type User struct {
	ID           int64       `json:"id"`
	Uuid         uuid.UUID   `json:"uuid"`
	Username     pgtype.Text `json:"username"`
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}
